#!/usr/bin/env python3
"""Generate src/iso8859_6.inc from the ISO-8859-6 -> MSX-font CSV.

Emits two tables covering ISO-8859-6 codes 0x80..0xFF (indexed by
code - 0x80):

    IsoMap: 128 entries of 4 bytes -> [Isolated, End, Initial, Middle]
    IsoJoin: 128 bytes -> bit0 = can_join_left  (connects to next letter)
                          bit1 = can_join_right (receives from previous)

Empty CSV columns fall back to Isolated so the four columns are always
safe to read. Non-Arabic codes (and codes outside 0xA1..0xF6) get
IsoJoin = 0, which the asm runtime treats as a word boundary.
"""
import csv, pathlib, sys

CSV  = pathlib.Path("ISO-8859-6 font mapping/ISO-8859-6-font-mapping.csv")
DEST = pathlib.Path("src/iso8859_6.inc")

ARABIC_LO = 0xA1
ARABIC_HI = 0xF6

# Arabic joining classes, driven by orthography rather than glyph shape
# (the MSX Al-Alamiah font collapses many dual-joiners to 2 forms, which
# would otherwise hide JOIN_RIGHT on letters like ب).
#   R = right-joining (connects to previous only)     -> JOIN_RIGHT
#   D = dual-joining  (connects to both sides)        -> JOIN_LEFT|JOIN_RIGHT
#   U = non-joining   (word-breaks on both sides)     -> 0
# Diacritics EB..F2 are treated as D so they don't break a word; their
# distinct "medial" glyph arrives naturally when between connected letters.
JOIN_CLASS = {
    0xC1: "U",  # ء hamza
    0xC2: "R",  # آ alef-madda
    0xC3: "R",  # أ alef-hamza-above
    0xC4: "R",  # ؤ waw-hamza
    0xC5: "R",  # إ alef-hamza-below
    0xC6: "D",  # ئ yeh-hamza
    0xC7: "R",  # ا alef
    0xC8: "D",  # ب
    0xC9: "R",  # ة teh-marbuta
    0xCA: "D",  # ت
    0xCB: "D",  # ث
    0xCC: "D",  # ج
    0xCD: "D",  # ح
    0xCE: "D",  # خ
    0xCF: "R",  # د
    0xD0: "R",  # ذ
    0xD1: "R",  # ر
    0xD2: "R",  # ز
    0xD3: "D",  # س
    0xD4: "D",  # ش
    0xD5: "D",  # ص
    0xD6: "D",  # ض
    0xD7: "D",  # ط
    0xD8: "D",  # ظ
    0xD9: "D",  # ع
    0xDA: "D",  # غ
    0xE0: "D",  # ـ tatweel
    0xE1: "D",  # ف
    0xE2: "D",  # ق
    0xE3: "D",  # ك
    0xE4: "D",  # ل
    0xE5: "D",  # م
    0xE6: "D",  # ن
    0xE7: "D",  # ه
    0xE8: "R",  # و
    0xE9: "R",  # ى
    0xEA: "D",  # ي
    # Diacritics: transparent, treated as dual-joiners for shaping.
    0xEB: "D", 0xEC: "D", 0xED: "D", 0xEE: "D", 0xEF: "D",
    0xF0: "D", 0xF1: "D", 0xF2: "D",
    # Lam-alef ligatures behave like alef (right-joining).
    0xF3: "R", 0xF4: "R", 0xF5: "R", 0xF6: "R",
}
# JOIN_LEFT = 0x01, JOIN_RIGHT = 0x02 (used by the shaper's form picker).
# IS_ARABIC = 0x04 flags any Arabic letter (joining OR non-joining like
# hamza) so the asm pass-buffer can keep non-joiners inside the word
# instead of treating them as word boundaries.
CLASS_FLAGS = {"U": 0x04, "R": 0x06, "D": 0x07}

def hx(s):
    s = (s or "").strip()
    return int(s, 16) if s else None

def main():
    rows = {}
    with CSV.open(newline="") as f:
        r = csv.reader(f)
        next(r)                                  # header
        for row in r:
            if not row or not row[0].strip():
                continue
            code = int(row[0], 16)
            iso  = hx(row[3])
            end  = hx(row[4]) if len(row) > 4 else None
            ini  = hx(row[5]) if len(row) > 5 else None
            mid  = hx(row[6]) if len(row) > 6 else None
            if iso is None:
                # empty row (no glyph at all) -> fall back to space
                iso = 0x20
            end = end if end is not None else iso
            ini = ini if ini is not None else iso
            mid = mid if mid is not None else end
            rows[code] = (iso, end, ini, mid)

    lines = [
        "; iso8859_6.inc - generated by tools/gen_iso8859_6.py",
        "; ISO-8859-6 byte -> MSX font glyph + joining flags.",
        "; Indexed by (code - 0x80).  4 bytes per entry: Iso, End, Ini, Mid.",
        "",
        "JOIN_LEFT  equ 0x01          ; connects to next letter",
        "JOIN_RIGHT equ 0x02          ; receives connection from previous",
        "IS_ARABIC  equ 0x04          ; any Arabic letter (keeps it inside a word)",
        "",
        "IsoMap:",
    ]

    for code in range(0x80, 0x100):
        r = rows.get(code, (0x20, 0x20, 0x20, 0x20))
        lines.append(
            f"    db 0x{r[0]:02X}, 0x{r[1]:02X}, 0x{r[2]:02X}, 0x{r[3]:02X}"
            f"   ; 0x{code:02X}"
        )

    lines += ["", "IsoJoin:"]

    join_row = []
    for code in range(0x80, 0x100):
        flags = CLASS_FLAGS.get(JOIN_CLASS.get(code, ""), 0x00)
        join_row.append((code, flags))

    # Emit 8 bytes per line for readability.
    for i in range(0, 128, 8):
        chunk = join_row[i:i+8]
        vals = ", ".join(f"0x{f:02X}" for _, f in chunk)
        lo = chunk[0][0]
        hi = chunk[-1][0]
        lines.append(f"    db {vals}   ; 0x{lo:02X}..0x{hi:02X}")

    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text("\n".join(lines) + "\n")
    print(f"wrote {DEST}  ({len(rows)} CSV rows)")

if __name__ == "__main__":
    main()
