#!/usr/bin/env python3
"""Pack resources/*.png into Screen-6 bitmap bytes and emit asm `db` data.

Screen 6 is 2 bpp (4 pixels per byte). Bits 7-6 are the leftmost pixel, 5-4
next, etc. Black pixels use value 3 (11 binary), bg pixels use value 1 (01
binary = COL_LGRAY, the button/scrollbar bg). A fully-black row packs to
0xFF; a fully-bg row packs to 0x55.

Refresh/stop icons target 20x10 MSX pixels (fits the 60x15 toolbar button
with breathing room; Screen 6 pixels are ~2:1 tall:narrow so 20x10 renders
as roughly square on screen). Up/down scrollbar arrows target 12x7 MSX
pixels (fits the 12x12 scrollbar arrow box).

Usage:
    python3 tools/icons_gen.py
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
COL_BLACK = 3       # pixel value 11 -> solid pal 3 = black
COL_BG = 1          # pixel value 01 -> solid pal 1 = light gray (button bg)
ALPHA_THRESHOLD = 128
LUMA_THRESHOLD = 128

ICONS = [
    ("IconRefresh", "resources/refresh.png", 20, 10),
    ("IconStop",    "resources/stop.png",    20, 10),
    # Only the up arrow is packed; DrawDownArrow flips it vertically at
    # draw time (see DrawBitmapReverse) to save ~10 bytes of data.
    ("IconUpArrow", "resources/up.png",       8,  5),
]


def pack_icon(path: Path, width: int, height: int) -> list[list[int]]:
    img = Image.open(path).convert("RGBA")
    img = img.resize((width, height), Image.LANCZOS)
    rows: list[list[int]] = []
    for y in range(height):
        row_bytes: list[int] = []
        for bx in range(0, width, 4):
            byte = 0
            for px in range(4):
                r, g, b, a = img.getpixel((bx + px, y))
                luma = (r + g + b) // 3
                is_black = a >= ALPHA_THRESHOLD and luma < LUMA_THRESHOLD
                color = COL_BLACK if is_black else COL_BG
                byte |= color << (6 - px * 2)
            row_bytes.append(byte)
        rows.append(row_bytes)
    return rows


def emit_label(label: str, rows: list[list[int]]) -> None:
    print(f"{label}:")
    for row in rows:
        hex_bytes = ", ".join(f"0x{b:02X}" for b in row)
        print(f"    db  {hex_bytes}")


def main() -> None:
    print("; Screen-6 icon bitmaps (4 px/byte, 11=black, 01=bg/lgray).")
    print("; Generated by tools/icons_gen.py.")
    for label, src, w, h in ICONS:
        print()
        print(f"; {src} -> {w}x{h} MSX pixels")
        emit_label(label, pack_icon(ROOT / src, w, h))


if __name__ == "__main__":
    main()
