#!/bin/bash
# Copy dist/mwbro.com and the sample HTML / text files into the MSX-DOS
# boot disk (overwriting any existing copies). MSX-DOS 1 uses 8.3 filenames.
set -euo pipefail
cd "$(dirname "$0")/.."
DISK="MSX-DOS/MSX-DOS v1.03.DSK"
# mtools refuses to write a read-only file; make it writable the first time.
chmod u+w "$DISK" 2>/dev/null || true
mcopy -i "$DISK" -o dist/mwbro.com ::/MWBRO.COM
# Current test set. Earlier exploratory samples (test1..test7, imgs2,
# logos, imgonly, txt) were retired when test8/test9/test10 started
# covering the same tags + Arabic/tables. Remove stale copies from the
# disk first so the root-dir slot budget fits the WEBSITE page set.
for stale in TEST1.HTM TEST2.HTM TEST3.HTM TEST4.HTM TEST5.HTM TEST6.HTM \
             TEST7.HTM IMGS2.HTM LOGOS.HTM IMGONLY.HTM TXT.TXT; do
    mdel -i "$DISK" "::/$stale" 2>/dev/null || true
done
mcopy -i "$DISK" -o samples/test.html  ::/TEST.HTM
# The 8.htm .. rtltab.htm regression pages are available in samples/ but
# aren't shipped to the floppy by default -- they collectively soak up
# ~40 KB + ~9 directory slots the web proxy needs for PG*.SC6. Re-add
# them here for rendering regression runs.
# Big image-format demo assets (IMAGE5.SC6, LENA8.PCX, BMP24.BMP,
# MSXLOGO.BMP) are kept in samples/ but NOT pushed to the floppy by
# default -- they ate ~190 KB of floppy space that the web proxy needs
# for long PG*.SC6 sets. Comment the `for stale` block out if you want
# the pcxtest / bmptest pages working on disk again.
for stale in IMAGE5.SC6 LENA8.PCX BMP24.BMP MSXLOGO.BMP PCXTEST.HTM BMPTEST.HTM; do
    mdel -i "$DISK" "::/$stale" 2>/dev/null || true
done
# SAKHR.SC6 + MSXLOGO.SC6 + the layout-regression HTMs stay in samples/
# but aren't auto-shipped -- again, the floppy needs room for PG*.SC6.
# Generated by tools/web_to_sc6.py (website snapshot + page wrapper).
# Filenames are PGnn.SC6 (one per logical viewport) so they stay
# within MSX-DOS 1's 8.3 FCB limit. Older PGnnA/PGnnB / PAGE* /
# WEBSITE* sets are wiped so the floppy doesn't waste slots on stale
# names.
for n in $(seq -f "%02g" 1 99); do
    mdel -i "$DISK" "::/PAGE${n}.SC6"    2>/dev/null || true
    mdel -i "$DISK" "::/WEBSITE${n}.SC6" 2>/dev/null || true
    for half in A B; do
        mdel -i "$DISK" "::/PG${n}${half}.SC6" 2>/dev/null || true
    done
done
mdel -i "$DISK" ::/PAGE.HTM     2>/dev/null || true
mdel -i "$DISK" ::/WEBSITE.HTM  2>/dev/null || true
if [ -f samples/PG.HTM ]; then
    mcopy -i "$DISK" -o samples/PG.HTM ::/PG.HTM
    # Floppy will run out of space / directory slots before the whole
    # page fits. Keep injecting until mcopy fails, then stop -- the
    # browser will render as many chunks as made it to disk and the
    # wrapper HTM's trailing <img src=...> tags simply fall back to
    # [alt] placeholders for missing files.
    for n in $(seq -f "%02g" 1 99); do
        src="samples/PG${n}.SC6"
        [ -f "$src" ] || continue
        if ! mcopy -i "$DISK" -o "$src" "::/PG${n}.SC6" 2>/dev/null; then
            echo "inject: floppy full at PG${n}.SC6" >&2
            break
        fi
    done
fi
